//! Generated by RFC 098 split.

use crate::escape;



/// A small stylesheet common to every page. Deliberately modest:
/// system font stack, high contrast, no vendor CSS reset.
pub const BASE_CSS: &str = r#"
:root {
  color-scheme: light dark;
  --bg: Canvas;
  --fg: CanvasText;
  --muted: GrayText;
  --accent: #2753c8;
  --err: #a6261d;

  /* v0.31.0: state tokens. Used by .flash--*, .badge--*, button.danger,
   * button.warning. Color values are derived from the v0.31.0 UI/UX
   * review materials (PNG #2 / #11) and tested for WCAG AA contrast
   * against --bg. Each foreground token is paired with a soft
   * background variant for flash/banner regions.
   *
   * IMPORTANT: never rely on color alone — every state has a
   * companion icon and text label per WCAG 1.4.1 (Use of Color).
   * The .flash and .badge templates emit these. */
  --success:    #1f9d55;
  --success-bg: #e8f5e9;
  --warning:    #b76e00;
  --warning-bg: #fff7e6;
  --danger:     #c92a2a;
  --danger-bg:  #fdecea;
  --info:       #1864ab;
  --info-bg:    #e7f5ff;
}

/* Dark-mode overrides. Light bg variants would wash out on a dark
 * canvas, so we shift to muted dark tints with the same hue family.
 * Foreground tokens get a brightness boost for contrast against the
 * dark canvas. Tested informally against macOS Dark Mode and Firefox
 * dark theme; if the deployment renders against an unusual canvas
 * (e.g., true #000), the legibility floor is still acceptable
 * because each state pairs color with text + icon. */
@media (prefers-color-scheme: dark) {
  :root {
    --success:    #4ade80;
    --success-bg: #14532d;
    --warning:    #fbbf24;
    --warning-bg: #78350f;
    --danger:     #f87171;
    --danger-bg:  #7f1d1d;
    --info:       #60a5fa;
    --info-bg:    #1e3a8a;
  }
}

* { box-sizing: border-box; }
html, body {
  margin: 0;
  padding: 0;
  background: var(--bg);
  color: var(--fg);
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  line-height: 1.5;
}
main {
  max-width: 28rem;
  margin: 3rem auto;
  padding: 1.5rem;
}
h1 { font-size: 1.5rem; margin: 0 0 1rem; }
p  { margin: 0 0 1rem; }
label { display: block; margin: 1rem 0 0.25rem; font-weight: 600; }
input[type="email"],
input[type="text"] {
  width: 100%;
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--muted);
  border-radius: 0.25rem;
  font: inherit;
  background: var(--bg);
  color: var(--fg);
}
input:focus { outline: 2px solid var(--accent); outline-offset: 2px; }
button {
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  border: 1px solid var(--accent);
  background: var(--accent);
  color: white;
  font: inherit;
  border-radius: 0.25rem;
  cursor: pointer;
}
button.secondary {
  background: var(--bg);
  color: var(--accent);
}
/* v0.31.0: explicit danger / warning button states. The disable-TOTP
 * confirmation page uses button.danger for the confirm action; future
 * destructive flows should reuse it rather than inlining colors. */
button.danger {
  border-color: var(--danger);
  background:   var(--danger);
  color:        white;
}
button.danger:focus  { outline: 2px solid var(--danger); outline-offset: 2px; }
button.warning {
  border-color: var(--warning);
  background:   var(--bg);
  color:        var(--warning);
}
button.warning:focus { outline: 2px solid var(--warning); outline-offset: 2px; }
button:focus { outline: 2px solid var(--accent); outline-offset: 2px; }

.error {
  color: var(--err);
  border-left: 3px solid var(--err);
  padding: 0.5rem 0.75rem;
  margin: 1rem 0;
}

/* v0.31.0: flash banners. One-shot notifications rendered from the
 * __Host-cesauth_flash cookie (see crates/worker/src/flash.rs). The
 * .flash root carries role + aria-live so screen readers announce
 * without a focus-grab; level-specific styling lives on the
 * modifier classes. Each flash MUST include an icon + text label
 * (the template enforces this) so the message is legible without
 * color perception. */
.flash {
  display: flex;
  align-items: flex-start;
  gap: 0.6rem;
  padding: 0.75rem 1rem;
  margin: 1rem 0;
  border-left: 4px solid var(--muted);
  border-radius: 0.25rem;
  background: var(--bg);
}
.flash--success { border-left-color: var(--success); background: var(--success-bg); color: var(--success); }
.flash--warning { border-left-color: var(--warning); background: var(--warning-bg); color: var(--warning); }
.flash--danger  { border-left-color: var(--danger);  background: var(--danger-bg);  color: var(--danger);  }
.flash--info    { border-left-color: var(--info);    background: var(--info-bg);    color: var(--info);    }
.flash__icon  { font-weight: bold; flex-shrink: 0; }
.flash__text  { flex: 1; }

/* v0.31.0: state badges. Used by the Security Center to label
 * TOTP enabled/disabled state and recovery code remaining count.
 * Same icon-plus-text rule as .flash. */
.badge {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  padding: 0.15rem 0.55rem;
  border-radius: 999px;
  font-size: 0.85em;
  font-weight: 600;
  border: 1px solid currentColor;
  background: var(--bg);
}
.badge--success { color: var(--success); }
.badge--warning { color: var(--warning); }
.badge--danger  { color: var(--danger);  }
.badge--info    { color: var(--info);    }

/* RFC 077: skip-to-content link (WCAG 2.4.1 Bypass Blocks).
 * Visually hidden until focused; slides in from above on focus. */
.skip-link {
  position: absolute;
  top: -100px;
  left: 0;
  padding: 0.5rem 1rem;
  background: var(--bg);
  color: var(--accent);
  text-decoration: underline;
  z-index: 1000;
  transition: top 0.15s ease-in-out;
}
.skip-link:focus {
  top: 0;
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

.muted { color: var(--muted); font-size: 0.9em; }
footer { margin-top: 3rem; color: var(--muted); font-size: 0.8em; text-align: center; }

/* Shared utility for screen-reader-only text. Used to attach an
 * accessible label to icons that visually convey state (the icon is
 * decorative, the text is the source of truth for assistive tech). */
.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

/* RFC 075: Security Center mobile state summary card.
 * Flex-wrapped badge list so badges reflow on narrow viewports. */
.security-summary__badges {
  list-style: none;
  padding: 0;
  margin: 0 0 1.5rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}
.security-summary__badges .badge__icon { flex-shrink: 0; }
.security-summary__badges .badge__text { white-space: nowrap; }
"#;

/// View model for [`flash_block`]. Carries the level + display
/// text + icon needed to render a flash banner. The struct is
/// constructed by the worker's `flash` module via its public API
/// — `cesauth-ui` does not depend on the worker, so the worker
/// builds the FlashView from its own [`Flash`] before handing it
/// to the renderer.
///
/// The `text` is a `&'static str` because the worker emits it
/// from a closed token table (see `cesauth_worker::flash::FlashKey`),
/// not from user-supplied input. The renderer therefore does NOT
/// escape it; pinned by tests in this module.
///
/// `aria_live` is `"polite"` or `"assertive"`. `css_modifier` is
/// `"flash--success"` etc. `icon` is a single Unicode glyph.
/// View model for [`flash_block`]. Carries the level + display
/// text the worker decided on; the template just slots it into
/// the standard banner element.
///
/// **v0.45.0** — `text` is `Cow<'static, str>` (was
/// `&'static str`). The owned variant carries
/// runtime-substituted strings such as the bulk-revoke
/// flash's count interpolation. The catalog's existing
/// parameter-free messages still flow through the borrowed
/// variant with no allocation, so the change is zero-cost
/// for the v0.31–v0.44 flashes.
///
/// **No longer `Copy`** as a consequence — `Cow` isn't.
/// `Clone` is preserved (bumps a refcount on the borrowed
/// variant, clones the buffer on the owned variant —
/// flash text is short and rare so the cost is irrelevant).
#[derive(Debug, Clone)]
pub struct FlashView {
    pub aria_live:    &'static str,
    pub css_modifier: &'static str,
    pub icon:         &'static str,
    pub text:         std::borrow::Cow<'static, str>,
}

/// Render a one-shot flash banner. Returns the empty string when
/// `view` is `None` so the caller can splice it into a body
/// unconditionally.
///
/// HTML shape:
///
/// ```html
/// <div class="flash flash--success" role="status" aria-live="polite">
///   <span class="flash__icon" aria-hidden="true">✓</span>
///   <span class="flash__text">TOTP を有効にしました。</span>
/// </div>
/// ```
///
/// Icon carries `aria-hidden="true"` because it's decorative —
/// screen readers announce the text. The accessibility floor is:
/// (a) a screen reader hears the text via aria-live, (b) a
/// sighted color-blind user reads the icon + text together with
/// the level conveyed by the colored border. Color is never the
/// sole carrier (WCAG 1.4.1).
pub fn flash_block(view: Option<FlashView>) -> String {
    let Some(v) = view else { return String::new(); };

    // role: alert for assertive, status for polite. Matches WAI-ARIA
    // best practice (role="alert" implies aria-live=assertive +
    // aria-atomic=true; we explicitly set aria-live anyway for
    // older AT compatibility).
    let role = if v.aria_live == "assertive" { "alert" } else { "status" };

    format!(
        r#"<div class="flash {modifier}" role="{role}" aria-live="{live}">
  <span class="flash__icon" aria-hidden="true">{icon}</span>
  <span class="flash__text">{text}</span>
</div>"#,
        modifier = v.css_modifier,
        role     = role,
        live     = v.aria_live,
        icon     = v.icon,
        text     = v.text,
    )
}

#[allow(dead_code)]
#[allow(dead_code)]
pub fn frame(title: &str, body: &str) -> String {
    frame_with_flash(title, "", body, cesauth_core::i18n::Locale::default())
}

pub fn frame_for(title: &str, body: &str, locale: cesauth_core::i18n::Locale) -> String {
    frame_with_flash(title, "", body, locale)
}

/// Like [`frame`] but allows the caller to splice a flash banner
/// at the top of `<main>`. `flash_html` should typically come from
/// [`flash_block`]; an empty string yields a flash-less page.
///
/// `locale` controls the `<html lang>` attribute (RFC 072).
pub fn frame_with_flash(title: &str, flash_html: &str, body: &str, locale: cesauth_core::i18n::Locale) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let nonce    = crate::render_nonce();
    let lang     = locale.bcp47();
    let skip_txt = escape(lookup(MessageKey::SkipToMainContent, locale));
    format!(
        r##"<!doctype html>
<html lang="{lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{title}</title>
  <style nonce="{nonce}">{css}</style>
</head>
<body>
<a href="#main" class="skip-link">{skip}</a>
<main id="main">
{flash}
{body}
</main>
<footer>cesauth</footer>
</body>
</html>
"##,
        lang  = lang,
        title = escape(title),
        css   = BASE_CSS,
        nonce = nonce,
        skip  = skip_txt,
        flash = flash_html,
        body  = body,
    )
}
