//! Generated by RFC 098 split.

use crate::{escape, js_string_literal};
use super::chrome::frame_for;

/// both would be error cases at the widget level).
pub fn login_page(
    csrf_token:        &str,
    error:             Option<&str>,
    turnstile_sitekey: Option<&str>,
) -> String {
    login_page_for(csrf_token, error, turnstile_sitekey, true, cesauth_core::i18n::Locale::default())
}

/// Locale-aware variant of [`login_page`] (v0.39.0). Every
/// visible string flows through `cesauth_core::i18n::lookup`.
/// The plain `login_page` shorthand defaults to `Locale::Ja`
/// to preserve the v0.36.0 backward-compat pattern. Pre-v0.39.0
/// `login_page` was hardcoded English; with v0.39.0 the
/// shorthand returns Japanese — the locale-less call site
/// retains the same Default = Ja semantics adopted in v0.36.0,
/// and English consumers move to `login_page_for(.., Locale::En)`
/// or rely on `Accept-Language` negotiation in the worker.
///
/// **RFC 079** — `magic_link_available`: when `false`, the Magic Link
/// email form is replaced by an informational notice. The operator
/// boundary is preserved — no delivery details are shown.
pub fn login_page_for(
    csrf_token:           &str,
    error:                Option<&str>,
    turnstile_sitekey:    Option<&str>,
    magic_link_available: bool,
    locale:               cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let nonce = crate::render_nonce();

    let err_region = match error {
        Some(msg) => format!(
            r#"<div class="error" role="alert" aria-live="assertive">{}</div>"#,
            escape(msg),
        ),
        None => String::from(
            r#"<div class="error" role="alert" aria-live="assertive" hidden></div>"#,
        ),
    };

    // Only emit the Turnstile bits when we actually have a sitekey.
    // An empty `data-sitekey=""` renders a broken widget.
    let (turnstile_script, turnstile_widget) = match turnstile_sitekey {
        Some(sk) if !sk.is_empty() => (
            String::from(
                r#"<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>"#,
            ),
            format!(
                r#"<div class="cf-turnstile" data-sitekey="{}"></div>"#,
                escape(sk),
            ),
        ),
        _ => (String::new(), String::new()),
    };

    // The inline script is tiny and purely progressive: the form works
    // without it. We still set `defer` so it runs after the DOM exists.
    //
    // **v0.39.0** — the JS error message comes from the catalog. We
    // emit it as a JS string literal (double-quoted with the few
    // characters that have meaning inside a double-quoted JS string
    // escaped). This stays correct even if a future translation
    // introduces double quotes / backslashes / newlines.
    let passkey_failed_js = js_string_literal(lookup(MessageKey::LoginPasskeyFailed, locale));

    // RFC 079: when MagicLinkMailer is not configured, replace the email form
    // with an informational notice. No provider details are revealed.
    let mail_section = if magic_link_available {
        format!(
            "<form method=\"POST\" action=\"{magic_link_request_url}\" aria-labelledby=\"mail-heading\">\n\
  <h2 id=\"mail-heading\" class=\"muted\">{email_heading}</h2>\n\
  <input type=\"hidden\" name=\"csrf\" value=\"{csrf}\">\n\
  <label for=\"email\">{email_label}</label>\n\
  <input id=\"email\" name=\"email\" type=\"email\" required autocomplete=\"email\"\n\
         inputmode=\"email\" spellcheck=\"false\">\n\
  {turnstile_widget}\n\
  <button type=\"submit\" class=\"secondary\">{email_button}</button>\n\
</form>",
            email_heading  = escape(lookup(MessageKey::LoginEmailHeading, locale)),
            email_label    = escape(lookup(MessageKey::LoginEmailLabel,   locale)),
            email_button   = escape(lookup(MessageKey::LoginEmailButton,  locale)),
            csrf           = escape(csrf_token),
            turnstile_widget = &turnstile_widget,
            magic_link_request_url = cesauth_core::routes::auth::MAGIC_LINK_REQUEST,
        )
    } else {
        format!(
            "<section aria-labelledby=\"mail-heading\">\n\
  <h2 id=\"mail-heading\" class=\"muted\">{email_heading}</h2>\n\
  <p class=\"flash flash--info\" role=\"status\">\n\
    <span class=\"flash__icon\" aria-hidden=\"true\">\u{00B7}</span>\n\
    <span class=\"flash__text\">{notice}</span>\n\
  </p>\n\
</section>",
            email_heading = escape(lookup(MessageKey::LoginEmailHeading, locale)),
            notice = escape(lookup(MessageKey::LoginMagicLinkUnavailableNotice, locale)),
        )
    };

    let body = format!(r#"
<h1>{title}</h1>
<p>{intro}</p>

{turnstile_script}

{err_region}

<noscript>
  <p class="muted">{js_required}</p>
</noscript>

<section aria-labelledby="passkey-heading">
  <h2 id="passkey-heading" class="muted">{passkey_heading}</h2>
  <button id="passkey-btn" type="button">{passkey_button}</button>
</section>

{mail_section}

<script defer nonce="{nonce}">
(async () => {{
  const btn = document.getElementById("passkey-btn");
  const err = document.querySelector(".error[role='alert']");
  if (!window.PublicKeyCredential) {{
    btn.disabled = true;
    return;
  }}
  btn.addEventListener("click", async () => {{
    err.hidden = true;
    try {{
      const r = await fetch({webauthn_start_url}, {{ method: "POST" }});
      if (!r.ok) throw new Error("could not start");
      const opts = await r.json();
      // navigator.credentials.get() expects ArrayBuffer values; convert.
      const cred = await navigator.credentials.get({{ publicKey: decode(opts.publicKey) }});
      const f = await fetch({webauthn_finish_url}, {{
        method: "POST",
        headers: {{ "content-type": "application/json" }},
        body: JSON.stringify(encode(cred)),
      }});
      if (!f.ok) throw new Error("authentication failed");
      window.location.href = "/";
    }} catch (e) {{
      err.textContent = {passkey_failed_js};
      err.hidden = false;
    }}
  }});

  // Minimal base64url <-> ArrayBuffer helpers. Intentionally inlined
  // to keep the page dependency-free.
  function b64urlToBuf(s) {{
    const p = s.length % 4 === 0 ? "" : "=".repeat(4 - s.length % 4);
    const b = atob((s + p).replace(/-/g, "+").replace(/_/g, "/"));
    const u = new Uint8Array(b.length);
    for (let i = 0; i < b.length; i++) u[i] = b.charCodeAt(i);
    return u.buffer;
  }}
  function bufToB64url(b) {{
    const u = new Uint8Array(b);
    let s = "";
    for (let i = 0; i < u.length; i++) s += String.fromCharCode(u[i]);
    return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  }}
  function decode(opts) {{
    const o = {{ ...opts }};
    o.challenge = b64urlToBuf(o.challenge);
    if (o.allowCredentials) o.allowCredentials = o.allowCredentials.map(c => (
      {{ ...c, id: b64urlToBuf(c.id) }}
    ));
    return o;
  }}
  function encode(cred) {{
    return {{
      id:     cred.id,
      rawId:  bufToB64url(cred.rawId),
      type:   cred.type,
      response: {{
        clientDataJSON:    bufToB64url(cred.response.clientDataJSON),
        authenticatorData: bufToB64url(cred.response.authenticatorData),
        signature:         bufToB64url(cred.response.signature),
        userHandle:        cred.response.userHandle ? bufToB64url(cred.response.userHandle) : null,
      }},
    }};
  }}
}})();
</script>
"#,
        title              = escape(lookup(MessageKey::LoginTitle,             locale)),
        intro              = escape(lookup(MessageKey::LoginIntro,             locale)),
        js_required        = escape(lookup(MessageKey::LoginPasskeyJsRequired, locale)),
        passkey_heading    = escape(lookup(MessageKey::LoginPasskeyHeading,    locale)),
        passkey_button     = escape(lookup(MessageKey::LoginPasskeyButton,     locale)),
        mail_section       = mail_section,
        passkey_failed_js  = passkey_failed_js,
        err_region         = err_region,
        turnstile_script   = turnstile_script,
        nonce              = nonce,
        webauthn_start_url  = js_string_literal(cesauth_core::routes::auth::PASSKEY_AUTH_START),
        webauthn_finish_url = js_string_literal(cesauth_core::routes::auth::PASSKEY_AUTH_FINISH),
    );

    frame_for(lookup(MessageKey::LoginPageTitleHtml, locale), &body, locale)
}

/// Page shown after a Magic Link has been sent. Does not reveal whether
/// the email existed (account enumeration mitigation).
///
/// `handle` is the AuthChallenge handle from the prior `/magic-link/request`
/// step. The verify endpoint needs it to look up the challenge.
/// `csrf_token` is the CSRF token (matching the
/// `__Host-cesauth-csrf` cookie) required by `/magic-link/verify`'s
/// form-encoded path. Both fields land as hidden inputs so the
/// browser carries them on submission.
///
/// Pre-v0.25.0 this template took no arguments and rendered a form
/// missing both fields, which made the form-flow path unusable in
/// browsers (the verify handler returns 400 on empty handle, and
/// the v0.24.0 CSRF gap fill rejects empty csrf). The path was
/// failing closed but invisible-to-users. v0.25.0 fixes the UX and
/// adds an end-to-end form test (see `tests.rs`).
pub fn magic_link_sent_page(handle: &str, csrf_token: &str) -> String {
    magic_link_sent_page_for(handle, csrf_token, cesauth_core::i18n::Locale::default())
}

/// **v0.47.0** — Locale-aware variant of
/// [`magic_link_sent_page`]. Pre-v0.47.0 this page was
/// EN-only despite cesauth's "default JA" pattern; the
/// migration to the catalog brings it in line with the
/// rest of the user-facing surfaces. The legacy
/// shorthand calls this with `Locale::default()` (Ja),
/// which is **a behavior change in display** for any
/// caller still on the shorthand — they previously got
/// English, now they get Japanese. The worker
/// handlers were already negotiating locale in v0.39.0
/// and pass through `_for`, so the production path is
/// unaffected.
pub fn magic_link_sent_page_for(
    handle: &str,
    csrf_token: &str,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let body = format!(
        r#"
<h1>{heading}</h1>
<p>{intro}</p>

<form method="POST" action="{verify_url}" aria-labelledby="otp-heading">
  <h2 id="otp-heading" class="muted">{otp_heading}</h2>
  <input type="hidden" name="handle" value="{handle}">
  <input type="hidden" name="csrf"   value="{csrf}">
  <label for="code">{code_label}</label>
  <input id="code" name="code" type="text" required autocomplete="one-time-code"
         inputmode="text" spellcheck="false" pattern="[A-Za-z0-9]{{6,12}}">
  <button type="submit">{submit}</button>
</form>
"#,
        heading     = escape(lookup(MessageKey::MagicLinkSentHeading,    locale)),
        intro       = escape(lookup(MessageKey::MagicLinkSentIntro,      locale)),
        otp_heading = escape(lookup(MessageKey::MagicLinkSentOtpHeading, locale)),
        code_label  = escape(lookup(MessageKey::MagicLinkSentCodeLabel,  locale)),
        submit      = escape(lookup(MessageKey::TotpVerifyContinueButton, locale)),
        handle      = escape(handle),
        csrf        = escape(csrf_token),
        verify_url  = cesauth_core::routes::auth::MAGIC_LINK_VERIFY_FORM,
    );
    frame_for(lookup(MessageKey::MagicLinkSentPageTitle, locale), &body, locale)
}

/// Generic error page. The worker layer maps specific errors to strings
/// (we do not leak internal detail here).
pub fn error_page(title: &str, detail: &str) -> String {
    error_page_for(title, detail, cesauth_core::i18n::Locale::default())
}

/// **v0.47.0** — Locale-aware variant of [`error_page`].
/// `title` and `detail` are caller-supplied (the worker
/// is responsible for localizing them before passing in);
/// only the "back to sign in" link is templated through
/// the catalog.
pub fn error_page_for(
    title: &str,
    detail: &str,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let body = format!(
        r#"<h1>{title}</h1>
<div class="error" role="alert" aria-live="assertive">{detail}</div>
<p><a href="/">{back}</a></p>"#,
        title  = escape(title),
        detail = escape(detail),
        back   = escape(lookup(MessageKey::ErrorPageBackLink, locale)),
    );
    frame_for(title, &body, locale)
}

// =====================================================================
