//! Generated by RFC 098 split.
//!
//! v0.67.0 (RFC 106): TOTP enabled-state badge / disable link / recovery
//! 0-and-1 banners are now sourced from the i18n catalog, closing the
//! JA-hardcode hole deferred from v0.39.0. The N≥2 recovery template
//! still carries `{n}` for substitution; true plural-form handling
//! waits for RFC 107 (ADR-013 §Q4).

use crate::escape;
use super::chrome::frame_with_flash;

// /me/security — Security Center index page (v0.31.0 P0-A)
// =====================================================================

/// Primary authentication method for the current session — used
/// by the Security Center to label "how you sign in". Surfaces
/// only as display copy; no security decision rides on this
/// value. Set by the worker from the session record.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PrimaryAuthMethod {
    /// WebAuthn / Passkey. Already MFA-strong (device possession
    /// + on-device user verification), so TOTP is bypassed in
    /// `complete_auth`.
    Passkey,
    /// Magic Link via email. TOTP gate applies on top of this.
    MagicLink,
    /// Anonymous trial principal. Cannot enroll TOTP; the page
    /// renders without TOTP controls.
    Anonymous,
}

impl PrimaryAuthMethod {
    /// **v0.31.0** — JA-default label. Pre-v0.47.0 this
    /// was the only accessor; locale-aware code now uses
    /// [`Self::label_for`]. Retained as the
    /// default-locale shorthand for callers that haven't
    /// been migrated to negotiated locales.
    #[allow(dead_code)]
    fn label(self) -> &'static str {
        self.label_for(cesauth_core::i18n::Locale::default())
    }

    /// **v0.47.0** — i18n-2 continuation. Locale-aware
    /// label dispatch. The Security Center template's
    /// `_for(.., locale)` variants thread their locale
    /// through to this getter.
    pub fn label_for(self, locale: cesauth_core::i18n::Locale) -> &'static str {
        use cesauth_core::i18n::{lookup, MessageKey};
        match self {
            Self::Passkey   => lookup(MessageKey::PrimaryAuthMethodPasskey,   locale),
            Self::MagicLink => lookup(MessageKey::PrimaryAuthMethodMagicLink, locale),
            Self::Anonymous => lookup(MessageKey::PrimaryAuthMethodAnonymous, locale),
        }
    }
}

/// View state for [`security_center_page`]. Built by the worker
/// handler from the session + TOTP repo lookups; the template is
/// a pure projection of this struct.
///
/// `recovery_codes_remaining` is the result of
/// `RecoveryRepo::count_remaining` for the current user. Only
/// meaningful when `totp_enabled` is `true` — the rendering
/// suppresses the recovery section when TOTP is off, since
/// unconfirmed users have no codes.
#[derive(Debug, Clone, Copy)]
pub struct SecurityCenterState {
    pub primary_method:           PrimaryAuthMethod,
    pub totp_enabled:             bool,
    pub recovery_codes_remaining: u32,
    /// **RFC 075** — Active session count for the current user.
    /// Populated by the worker handler via the session-index store.
    /// `None` if the count is unavailable (e.g. DO temporarily unreachable).
    pub active_sessions_count:    Option<u32>,
}

/// Render the Security Center index page.
///
/// Design rules (plan v2 §3.1 P0-A):
///
/// - **Single task per page**: this page only displays state and
///   links to specialized actions (`/me/security/totp/enroll`,
///   `/me/security/totp/disable`). No enrollment, disable, or
///   recovery flow runs from here directly.
/// - **State as text + icon + color** (WCAG 1.4.1): every badge
///   carries an icon glyph + label, never color alone.
/// - **Recovery threshold**: N=10 / 2-9 → info; N=1 → warning;
///   N=0 → danger. The threshold rationale is in plan §3.1 P0-A.
///   No early "you should re-enroll" pressure because the
///   re-enrollment path is heavy.
/// - **Anonymous users**: the TOTP section is hidden; they see
///   only their primary-method label + a hint that TOTP becomes
///   available after promotion.
pub fn security_center_page(state: &SecurityCenterState) -> String {
    security_center_page_with_flash(state, "")
}

/// Same as [`security_center_page`] but allows the caller to
/// splice a flash banner above the page content. The Security
/// Center handler builds the banner from
/// `__Host-cesauth_flash`; other callers can pass `""` to get
/// the flash-less rendering (matching the legacy entry point).
pub fn security_center_page_with_flash(
    state:      &SecurityCenterState,
    flash_html: &str,
) -> String {
    security_center_page_for(state, flash_html, cesauth_core::i18n::Locale::default())
}

/// Locale-aware variant (v0.39.0). Every visible string flows
/// through `cesauth_core::i18n::lookup`. The callers above are
/// default-locale shorthands.
pub fn security_center_page_for(
    state:      &SecurityCenterState,
    flash_html: &str,
    locale:     cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    // ── RFC 075: mobile state summary card ────────────────────────────────
    // Badge tokens: passkey state, TOTP state, recovery count, sessions count.
    // Each badge carries icon + text (WCAG 1.4.1 — no color-only status).

    let passkey_badge = {
        let (token, icon, label) = match state.primary_method {
            PrimaryAuthMethod::Passkey    => ("success", "✓", lookup(MessageKey::SecuritySummaryPasskeyOk,       locale)),
            PrimaryAuthMethod::Anonymous  => ("info",    "·", lookup(MessageKey::SecuritySummaryPasskeyAnonymous, locale)),
            PrimaryAuthMethod::MagicLink  => ("warning", "◇", lookup(MessageKey::SecuritySummaryPasskeyMagicLink, locale)),
        };
        format!(r#"<li><span class="badge badge--{token}"><span class="badge__icon" aria-hidden="true">{icon}</span><span class="badge__text">{label}</span></span></li>"#,
            token = token, icon = icon, label = escape(label))
    };

    let totp_badge = if !matches!(state.primary_method, PrimaryAuthMethod::Anonymous) {
        let (token, icon, label) = if state.totp_enabled {
            ("success", "✓", lookup(MessageKey::SecuritySummaryTotpEnabled, locale))
        } else {
            ("warning", "△", lookup(MessageKey::SecuritySummaryTotpDisabled, locale))
        };
        format!(r#"<li><span class="badge badge--{token}"><span class="badge__icon" aria-hidden="true">{icon}</span><span class="badge__text">{label}</span></span></li>"#,
            token = token, icon = icon, label = escape(label))
    } else {
        String::new()
    };

    let recovery_badge = if state.totp_enabled {
        let n = state.recovery_codes_remaining;
        let (token, icon) = if n == 0 { ("danger", "✗") }
                            else if n <= 2 { ("warning", "△") }
                            else { ("success", "✓") };
        let template = lookup(MessageKey::SecuritySummaryRecovery, locale);
        let label = template.replace("{n}", &n.to_string());
        format!(r#"<li><span class="badge badge--{token}"><span class="badge__icon" aria-hidden="true">{icon}</span><span class="badge__text">{label}</span></span></li>"#,
            token = token, icon = icon, label = escape(&label))
    } else {
        String::new()
    };

    let sessions_badge = match state.active_sessions_count {
        Some(n) => {
            let template = lookup(MessageKey::SecuritySummarySessions, locale);
            let label = template.replace("{n}", &n.to_string());
            format!(r#"<li><span class="badge badge--info"><span class="badge__icon" aria-hidden="true">▣</span><span class="badge__text">{label}</span></span></li>"#,
                label = escape(&label))
        }
        None => String::new(),
    };

    let summary_card = format!(
        r#"<section class="security-summary" aria-labelledby="summary-heading">
  <h2 id="summary-heading" class="visually-hidden">{heading}</h2>
  <ul class="security-summary__badges">{passkey}{totp}{recovery}{sessions}</ul>
</section>"#,
        heading  = escape(lookup(MessageKey::SecuritySummaryHeading, locale)),
        passkey  = passkey_badge,
        totp     = totp_badge,
        recovery = recovery_badge,
        sessions = sessions_badge,
    );

    let primary_row = format!(
        r#"<section class="security-row" aria-labelledby="primary-heading">
  <h2 id="primary-heading">{heading}</h2>
  <p>{label}</p>
</section>"#,
        heading = escape(lookup(MessageKey::SecurityPrimaryHeading, locale)),
        label   = escape(state.primary_method.label_for(locale)),
    );

    let totp_section = match state.primary_method {
        PrimaryAuthMethod::Anonymous => format!(
            r#"<section class="security-row" aria-labelledby="totp-heading">
  <h2 id="totp-heading">{heading}</h2>
  <p class="muted">{notice}</p>
</section>"#,
            heading = escape(lookup(MessageKey::SecurityTotpHeading,           locale)),
            notice  = escape(lookup(MessageKey::SecurityTotpAnonymousNotice,   locale)),
        ),
        _ => totp_section_html_for(state.totp_enabled, state.recovery_codes_remaining, locale),
    };

    let body = format!(
        r#"<h1>{title}</h1>
<p class="muted">{intro}</p>

{summary_card}

{primary_row}

{totp_section}

<section class="security-row" aria-labelledby="sessions-heading">
  <h2 id="sessions-heading">{sessions_heading}</h2>
  <p>{sessions_intro}</p>
  <p><a href="/me/security/sessions">{sessions_link}</a></p>
</section>

<p class="muted"><a href="/">{back}</a></p>"#,
        title            = escape(lookup(MessageKey::SecurityTitle,            locale)),
        intro            = escape(lookup(MessageKey::SecurityIntro,            locale)),
        sessions_heading = escape(lookup(MessageKey::SecuritySessionsHeading,  locale)),
        sessions_intro   = escape(lookup(MessageKey::SecuritySessionsIntro,    locale)),
        sessions_link    = escape(lookup(MessageKey::SecuritySessionsLink,     locale)),
        back             = escape(lookup(MessageKey::SecurityBackLink,         locale)),
        summary_card     = summary_card,
        primary_row      = primary_row,
        totp_section     = totp_section,
    );
    frame_with_flash(lookup(MessageKey::SecurityPageTitleHtml, locale), flash_html, &body, locale)
}

/// TOTP subsection of the Security Center. Branches on
/// `enabled`; when enabled, also renders the recovery-codes
/// status row with the 4-tier threshold treatment from plan
/// §3.1 P0-A.
///
/// **RFC 106 (v0.67.0)** — Every visible string now flows through
/// the i18n catalog, closing the JA-hardcode hole that v0.39.0
/// deferred. The N≥2 recovery template still carries `{n}` for
/// substitution; true plural-form handling is RFC 107's scope.
fn totp_section_html_for(
    enabled: bool,
    recovery_remaining: u32,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    if !enabled {
        return format!(
            r#"<section class="security-row" aria-labelledby="totp-heading">
  <h2 id="totp-heading">{heading}</h2>
  <p>
    <span class="badge badge--info">
      <span aria-hidden="true">ⓘ</span>
      <span>{badge}</span>
    </span>
  </p>
  <p>{intro}</p>
  <p><a href="/me/security/totp/enroll">{enable_link}</a></p>
</section>"#,
            heading     = escape(lookup(MessageKey::SecurityTotpHeading,         locale)),
            badge       = escape(lookup(MessageKey::SecurityTotpDisabledBadge,   locale)),
            intro       = escape(lookup(MessageKey::SecurityTotpDisabledIntro,   locale)),
            enable_link = escape(lookup(MessageKey::SecurityTotpEnableLink,      locale)),
        );
    }

    let recovery_row = recovery_status_html_for(recovery_remaining, locale);

    // Enabled path — all visible strings via the catalog (RFC 106).
    format!(
        r#"<section class="security-row" aria-labelledby="totp-heading">
  <h2 id="totp-heading">{heading}</h2>
  <p>
    <span class="badge badge--success">
      <span aria-hidden="true">✓</span>
      <span>{enabled_badge}</span>
    </span>
  </p>
  {recovery_row}
  <p><a href="/me/security/totp/disable">{disable_link}</a></p>
</section>"#,
        heading       = escape(cesauth_core::i18n::lookup(
            cesauth_core::i18n::MessageKey::SecurityTotpHeading,       locale)),
        enabled_badge = escape(cesauth_core::i18n::lookup(
            cesauth_core::i18n::MessageKey::SecurityTotpEnabledBadge,  locale)),
        disable_link  = escape(cesauth_core::i18n::lookup(
            cesauth_core::i18n::MessageKey::SecurityTotpDisableLink,   locale)),
        recovery_row  = recovery_row,
    )
}

/// Recovery-codes status block. Four-tier rendering per plan
/// §3.1 P0-A:
///
/// - N=10 → info badge, no supporting text (initial state).
/// - N=2–9 → info badge with the count, no supporting text.
/// - N=1 → warning badge + supporting text encouraging
///   re-enrollment. This is the first tier where the action
///   ("re-enroll") is truly justified.
/// - N=0 → danger badge + clear "operator contact required"
///   message.
///
/// All visible strings come from the i18n catalog (RFC 106 closure of
/// the v0.39.0 deferral). The N=1 / N=0 banners use a paired strong-title
/// + detail pattern (`SecurityRecoveryZeroTitle` + `SecurityRecoveryZeroDetail`,
/// and similarly for N=1) so translators can adjust emphasis independently.
/// The N≥2 path interpolates `{n}` into `SecurityRecoveryRemaining`;
/// true plural-form handling waits for RFC 107.
fn recovery_status_html_for(n: u32, locale: cesauth_core::i18n::Locale) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    match n {
        0 => format!(
            r#"<div class="flash flash--danger" role="alert" aria-live="assertive">
    <span class="flash__icon" aria-hidden="true">⛔</span>
    <span class="flash__text">
      <strong>{title}</strong>
      {detail}
    </span>
  </div>"#,
            title  = escape(lookup(MessageKey::SecurityRecoveryZeroTitle,  locale)),
            detail = escape(lookup(MessageKey::SecurityRecoveryZeroDetail, locale)),
        ),

        1 => format!(
            r#"<div class="flash flash--warning" role="alert" aria-live="assertive">
    <span class="flash__icon" aria-hidden="true">⚠</span>
    <span class="flash__text">
      <strong>{title}</strong>
      {detail}
    </span>
  </div>"#,
            title  = escape(lookup(MessageKey::SecurityRecoveryOneTitle,  locale)),
            detail = escape(lookup(MessageKey::SecurityRecoveryOneDetail, locale)),
        ),

        n => {
            let template = lookup(MessageKey::SecurityRecoveryRemaining, locale);
            let label = template.replace("{n}", &n.to_string());
            format!(
                r#"<p>
    <span class="badge badge--info">
      <span aria-hidden="true">ⓘ</span>
      <span>{label}</span>
    </span>
  </p>"#,
                label = escape(&label),
            )
        }
    }
}


// =====================================================================
// v0.35.0 — /me/security/sessions page
// =====================================================================

/// One row in the active-sessions list. The handler builds these
/// from `SessionState` rows returned by
/// `ActiveSessionStore::list_for_user`. Kept here (vs. importing
/// `SessionState` directly) so the template's contract is
/// surface-stable: future changes to `SessionState` shape won't
/// silently change what the user sees.
#[derive(Debug, Clone)]
pub struct SessionListItem {
    pub session_id:    String,
    pub auth_method:   String,   // "passkey" | "magic_link" | "admin"
    pub client_id:     String,   // displayed; empty string is fine
    pub created_at:    i64,      // Unix seconds
    pub last_seen_at:  i64,      // Unix seconds; matches created_at on D1-projected rows
    /// `true` if this row is the session that's currently
    /// rendering the page. Surfaced as a "this device" badge
    /// and disables the row's revoke button (revoking your
    /// current session would just log you out — handle that
    /// via the regular logout flow).
    pub is_current:    bool,
}

pub fn sessions_page(
    items:      &[SessionListItem],
    csrf_token: &str,
    flash_html: &str,
) -> String {
    sessions_page_for(items, csrf_token, flash_html, cesauth_core::i18n::Locale::default())
}

/// Locale-aware variant of [`sessions_page`]. **v0.36.0** —
/// every visible string flows through
/// `cesauth_core::i18n::lookup`. The plain `sessions_page`
/// shorthand defaults to `Locale::Ja` to preserve the
/// pre-i18n rendering for callers (and tests) that haven't
/// been migrated to negotiated locales.
pub fn sessions_page_for(
    items:      &[SessionListItem],
    csrf_token: &str,
    flash_html: &str,
    locale:     cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    let rows = if items.is_empty() {
        format!(
            r##"<p class="muted">{empty}</p>"##,
            empty = escape(lookup(MessageKey::SessionsPageEmpty, locale)),
        )
    } else {
        items.iter()
            .map(|s| render_session_row_for(s, csrf_token, locale))
            .collect::<Vec<_>>()
            .join("\n")
    };

    // **v0.45.0** — bulk revoke (ADR-012 §Q4).
    //
    // Button shown only when the user has at least one
    // OTHER active session. With just the current
    // session there's nothing to revoke; rendering the
    // button anyway would either be a no-op (annoying)
    // or accidentally revoke the current session
    // (worse). The check `any(|s| !s.is_current)` is
    // O(n) over a list capped at 50 — trivially cheap.
    //
    // Confirmation copy goes inline above the button
    // (no JS prompt — keeps the page progressive-
    // enhancement-clean). The phrasing is intentionally
    // direct: "all other devices will be signed out"
    // tells the user what's about to happen without
    // hedging.
    let bulk_button = if items.iter().any(|s| !s.is_current) {
        format!(
            r##"<section class="security-section bulk-revoke" aria-label="Bulk revoke other sessions">
  <p class="muted">{confirm}</p>
  <form method="post" action="/me/security/sessions/revoke-others" class="inline-form">
    <input type="hidden" name="csrf" value="{csrf}">
    <button type="submit" class="warning">{label}</button>
  </form>
</section>"##,
            confirm = escape(lookup(MessageKey::SessionsRevokeOthersConfirm, locale)),
            csrf    = escape(csrf_token),
            label   = escape(lookup(MessageKey::SessionsRevokeOthersButton, locale)),
        )
    } else {
        String::new()
    };

    let body = format!(
        r##"<h1>{title}</h1>
<p class="muted">{intro}</p>

<section class="security-section" aria-label="Active sessions">
  {rows}
</section>

{bulk_button}

<p class="muted">
  <a href="/me/security">{back}</a>
</p>
<p class="muted" role="note" style="font-size:0.8em;margin-top:1rem">{drift_note}</p>"##,
        title      = escape(lookup(MessageKey::SessionsPageTitle,  locale)),
        intro      = escape(lookup(MessageKey::SessionsPageIntro,  locale)),
        back       = escape(lookup(MessageKey::SessionsBackLink,   locale)),
        drift_note = escape(lookup(MessageKey::SessionsDriftNote,  locale)),
        rows       = rows,
        bulk_button = bulk_button,
    );

    let page_title = format!(
        "{} - cesauth",
        lookup(MessageKey::SessionsPageTitle, locale),
    );
    frame_with_flash(&page_title, flash_html, &body, locale)
}

#[allow(dead_code)]
fn render_session_row(s: &SessionListItem, csrf_token: &str) -> String {
    render_session_row_for(s, csrf_token, cesauth_core::i18n::Locale::default())
}

fn render_session_row_for(
    s:          &SessionListItem,
    csrf_token: &str,
    locale:     cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    let method_label = match s.auth_method.as_str() {
        "passkey"    => lookup(MessageKey::SessionsAuthMethodPasskey,   locale),
        "magic_link" => lookup(MessageKey::SessionsAuthMethodMagicLink, locale),
        "admin"      => lookup(MessageKey::SessionsAuthMethodAdmin,     locale),
        _            => lookup(MessageKey::SessionsAuthMethodUnknown,   locale),
    };
    let created = format_unix_local(s.created_at);
    let last    = format_unix_local(s.last_seen_at);

    let badge = if s.is_current {
        format!(
            r##"<span class="badge badge--current" aria-label="{badge_text}">{badge_text}</span>"##,
            badge_text = escape(lookup(MessageKey::SessionsCurrentBadge, locale)),
        )
    } else {
        String::new()
    };

    // Current session's revoke button is disabled — the user
    // should log out via the normal flow instead. If we let
    // them revoke their own session, the next request would
    // redirect to /login and the action would feel
    // self-defeating; logout-via-known-button is better UX.
    let action = if s.is_current {
        format!(
            r##"<button type="button" class="muted" disabled aria-disabled="true" title="{title}">{label}</button>"##,
            title = escape(lookup(MessageKey::SessionsCurrentDisabledTitle, locale)),
            label = escape(lookup(MessageKey::SessionsCurrentDisabled,      locale)),
        )
    } else {
        format!(
            r##"<form method="post" action="/me/security/sessions/{sid}/revoke" class="inline-form">
  <input type="hidden" name="csrf" value="{csrf}">
  <button type="submit" class="warning">{revoke}</button>
</form>"##,
            sid    = escape(&s.session_id),
            csrf   = escape(csrf_token),
            revoke = escape(lookup(MessageKey::SessionsRevokeButton, locale)),
        )
    };

    format!(
        r##"<article class="session-card" aria-label="セッション {sid}">
  <header>
    <strong>{method}</strong> {badge}
  </header>
  <dl class="session-meta">
    <dt>{l_signin}</dt><dd>{created}</dd>
    <dt>{l_last}</dt><dd>{last}</dd>
    <dt>{l_client}</dt><dd><code>{client}</code></dd>
    <dt>{l_sid}</dt><dd><code>{sid_short}</code></dd>
  </dl>
  <footer>{action}</footer>
</article>"##,
        sid       = escape(&s.session_id),
        sid_short = escape(&shorten_id(&s.session_id)),
        method    = escape(method_label),
        badge     = badge,
        created   = escape(&created),
        last      = escape(&last),
        client    = escape(&s.client_id),
        action    = action,
        l_signin  = escape(lookup(MessageKey::SessionsLabelSignIn,     locale)),
        l_last    = escape(lookup(MessageKey::SessionsLabelLastSeen,   locale)),
        l_client  = escape(lookup(MessageKey::SessionsLabelClient,     locale)),
        l_sid     = escape(lookup(MessageKey::SessionsLabelSessionId,  locale)),
    )
}

/// Format a Unix-seconds timestamp as ISO-8601 UTC. The user
/// page is otherwise localized JA, but timestamp formatting
/// stays UTC because cesauth has no per-user timezone yet —
/// see ROADMAP i18n track for that future work.
fn format_unix_local(unix: i64) -> String {
    use time::format_description::well_known::Rfc3339;
    time::OffsetDateTime::from_unix_timestamp(unix)
        .ok()
        .and_then(|d| d.format(&Rfc3339).ok())
        .unwrap_or_else(|| unix.to_string())
}

/// Truncate a UUID-shaped session_id to the first 8 chars for
/// display. The full id is in the form action's URL; the
/// shortened version is just visual chrome.
fn shorten_id(id: &str) -> String {
    let mut out: String = id.chars().take(8).collect();
    if id.chars().count() > 8 { out.push('…'); }
    out
}


