//! Generated by RFC 098 split.

use crate::escape;
use super::chrome::frame_for;

// TOTP enrollment + verify pages (v0.28.0)
// =====================================================================

/// TOTP enrollment page. Shown by `GET /me/security/totp/enroll`
/// after a fresh secret has been minted and an unconfirmed
/// `totp_authenticators` row parked.
///
/// The user scans `qr_svg` with their authenticator app (or
/// types `secret_b32` manually if they can't scan), then enters
/// the displayed code into the form which POSTs to
/// `/me/security/totp/enroll/confirm`.
///
/// The QR code is server-rendered SVG (no JavaScript dependency,
/// no third-party CDN). `qr_svg` is the raw `<svg>...</svg>`
/// payload which we inline into the page (it's already trusted
/// — generated by our own code, not user input — but we still
/// avoid escaping it so the SVG renders).
///
/// `csrf_token` matches the `__Host-cesauth-csrf` cookie value
/// for the POST guard.
///
/// `error`: optional inline error rendered above the confirm form.
/// Set to `Some(msg)` when the previous confirm POST failed (wrong
/// code or replay-protection rejection); `None` for the initial
/// render. Mirrors the `totp_verify_page` shape so handlers across
/// the TOTP flow have a uniform error surface.
///
/// When `error` is `Some`, the code input keeps `autofocus` so the
/// user lands on the form field after the page re-renders. Pin
/// reasoning: a wrong code mid-enrollment means the user already
/// has the authenticator app open; sending them back to the QR
/// code is wasted motion. Focus on the input invites the next
/// fresh code.
pub fn totp_enroll_page(
    qr_svg:     &str,
    secret_b32: &str,
    csrf_token: &str,
    error:      Option<&str>,
) -> String {
    totp_enroll_page_for(qr_svg, secret_b32, csrf_token, error,
        cesauth_core::i18n::Locale::default())
}

/// Locale-aware variant of [`totp_enroll_page`] (v0.39.0).
pub fn totp_enroll_page_for(
    qr_svg:     &str,
    secret_b32: &str,
    csrf_token: &str,
    error:      Option<&str>,
    locale:     cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    let err_block = match error {
        Some(msg) => format!(
            r#"<div class="error" role="alert" aria-live="assertive">{}</div>"#,
            escape(msg),
        ),
        None => String::new(),
    };

    let body = format!(
        r#"<h1>{title}</h1>
<p>{intro}</p>

<figure class="qr-figure" aria-label="{qr_aria}">
{qr_svg}
</figure>

<details>
  <summary>{manual_summary}</summary>
  <p class="muted">{manual_meta}</p>
  <pre class="totp-secret"><code>{secret}</code></pre>
</details>

{err_block}

<form method="POST" action="/me/security/totp/enroll/confirm" aria-labelledby="confirm-heading">
  <h2 id="confirm-heading">{confirm_heading}</h2>
  <p>{confirm_intro}</p>
  <input type="hidden" name="csrf" value="{csrf}">
  <label for="code">{code_label}</label>
  <input id="code" name="code" type="text" required autocomplete="one-time-code"
         inputmode="numeric" pattern="[0-9]{{6}}" maxlength="6"
         spellcheck="false" autofocus>
  <button type="submit">{confirm_button}</button>
</form>

<p class="muted"><a href="/">{cancel}</a></p>"#,
        title           = escape(lookup(MessageKey::TotpEnrollTitle,           locale)),
        intro           = escape(lookup(MessageKey::TotpEnrollIntro,           locale)),
        qr_aria         = escape(lookup(MessageKey::TotpEnrollQrAriaLabel,     locale)),
        manual_summary  = escape(lookup(MessageKey::TotpEnrollManualSummary,   locale)),
        manual_meta     = escape(lookup(MessageKey::TotpEnrollManualMeta,      locale)),
        confirm_heading = escape(lookup(MessageKey::TotpEnrollConfirmHeading,  locale)),
        confirm_intro   = escape(lookup(MessageKey::TotpEnrollConfirmIntro,    locale)),
        code_label      = escape(lookup(MessageKey::TotpEnrollCodeLabel,       locale)),
        confirm_button  = escape(lookup(MessageKey::TotpEnrollConfirmButton,   locale)),
        cancel          = escape(lookup(MessageKey::TotpEnrollCancelLink,      locale)),
        qr_svg    = qr_svg, // pre-validated SVG, intentionally NOT escaped
        secret    = escape(secret_b32),
        err_block = err_block,
        csrf      = escape(csrf_token),
    );
    frame_for(lookup(MessageKey::TotpEnrollPageTitleHtml, locale), &body, locale)
}

/// Recovery-codes display page. Shown ONCE after successful
/// enrollment confirmation. `codes` are the plaintext recovery
/// codes minted in this enrollment; this is the only time the
/// user will ever see them.
///
/// The page emphasizes this with strong visual treatment and a
/// confirm checkbox. There is no "show again" path — that's the
/// whole point of the at-rest hash. If the user navigates away
/// before saving, they have to disable TOTP and re-enroll to
/// get fresh codes.
pub fn totp_recovery_codes_page(codes: &[String]) -> String {
    totp_recovery_codes_page_for(codes, "", cesauth_core::i18n::Locale::default())
}

/// **v0.47.0** — Locale-aware variant of
/// [`totp_recovery_codes_page`]. The codes themselves
/// don't pass through the catalog (they're high-entropy
/// alphanumeric strings, locale-invariant); only the
/// surrounding chrome and warning copy do.
pub fn totp_recovery_codes_page_for(
    codes:       &[String],
    csrf_token:  &str,
    locale:      cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let nonce = crate::render_nonce();
    let codes_html: String = codes.iter()
        .map(|c| format!("<li><code>{}</code></li>", escape(c)))
        .collect::<Vec<_>>()
        .join("\n");

    // RFC 076: save-confirmation gate.
    // The proceed button starts disabled; JS enables it when the
    // checkbox is checked. Without JS, `required` on the checkbox
    // enforces native browser validation. Server-side validation
    // checks `saved_confirm=on` in the POST body (in the worker handler).
    let body = format!(
        r#"<h1>{heading}</h1>
<div class="warning" role="alert" aria-live="assertive">
  <strong>{alert_strong}</strong>
  {alert_body}
</div>

<ul class="totp-recovery-codes">
{codes}
</ul>

<p>{body_text}</p>

<form method="POST" action="/me/security/totp/recover/confirm">
  <input type="hidden" name="csrf"         value="{csrf}">
  <fieldset class="save-gate">
    <legend class="visually-hidden">{gate_legend}</legend>
    <label class="save-gate__label">
      <input id="saved-confirm"
             name="saved_confirm"
             type="checkbox"
             required>
      <span>{confirm_label}</span>
    </label>
  </fieldset>
  <button id="proceed-btn" type="submit" class="secondary" disabled>{proceed_btn}</button>
</form>

<script defer nonce="{nonce}">
(function() {{
  var cb  = document.getElementById('saved-confirm');
  var btn = document.getElementById('proceed-btn');
  if (cb && btn) {{
    cb.addEventListener('change', function() {{ btn.disabled = !cb.checked; }});
  }}
}})();
</script>"#,
        heading      = escape(lookup(MessageKey::TotpRecoveryCodesHeading,     locale)),
        alert_strong = escape(lookup(MessageKey::TotpRecoveryCodesAlertStrong, locale)),
        alert_body   = escape(lookup(MessageKey::TotpRecoveryCodesAlertBody,   locale)),
        body_text    = escape(lookup(MessageKey::TotpRecoveryCodesBody,        locale)),
        gate_legend  = "保存確認",  // admin-side is JA; end-user route is also fine with short literal
        confirm_label= escape(lookup(MessageKey::TotpRecoverySavedConfirmLabel, locale)),
        proceed_btn  = escape(lookup(MessageKey::TotpRecoveryProceedButton,    locale)),
        codes        = codes_html,
        csrf         = escape(csrf_token),
        nonce        = nonce,
    );
    frame_for(lookup(MessageKey::TotpRecoveryCodesPageTitle, locale), &body, locale)
}

/// TOTP verify page. Shown by `GET /me/security/totp/verify`
/// when the post-MagicLink gate has parked a `PendingTotp`
/// challenge. The user enters their current 6-digit code, the
/// form POSTs to the same path, and on success the original
/// authentication flow resumes (session start, AR redirect).
///
/// `csrf_token` matches the `__Host-cesauth-csrf` cookie. The
/// pending TOTP handle is carried in the `__Host-cesauth_totp`
/// cookie set by `complete_auth`, NOT in the form (it's
/// session state, not user input).
///
/// `error` is `None` for the initial page render; `Some(message)`
/// when the previous attempt's code was invalid (so the page
/// can show the error inline). Pre-empted attempts (cookie
/// missing / challenge expired) redirect to `/login` rather
/// than re-render this page.
pub fn totp_verify_page(csrf_token: &str, error: Option<&str>) -> String {
    totp_verify_page_for(csrf_token, error, cesauth_core::i18n::Locale::default())
}

/// Locale-aware variant of [`totp_verify_page`] (v0.39.0).
pub fn totp_verify_page_for(
    csrf_token: &str,
    error:      Option<&str>,
    locale:     cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    let error_block = match error {
        Some(msg) => format!(
            r#"<div class="error" role="alert" aria-live="assertive">{}</div>"#,
            escape(msg)
        ),
        None => String::new(),
    };

    let body = format!(
        r#"<h1>{title}</h1>
<p>{intro}</p>

{error_block}

<form method="POST" action="/me/security/totp/verify" aria-labelledby="verify-heading">
  <h2 id="verify-heading" class="muted">{heading}</h2>
  <input type="hidden" name="csrf" value="{csrf}">
  <label for="code">{code_label}</label>
  <input id="code" name="code" type="text" required autocomplete="one-time-code"
         inputmode="numeric" pattern="[0-9]{{6}}" maxlength="6"
         spellcheck="false" autofocus>
  <button type="submit">{continue_button}</button>
</form>

<details class="muted">
  <summary>{lost_summary}</summary>
  <p>{recover_intro}</p>
  <form method="POST" action="/me/security/totp/recover" aria-labelledby="recover-heading">
    <span id="recover-heading" class="visually-hidden">{recover_aria}</span>
    <input type="hidden" name="csrf" value="{csrf}">
    <label for="recovery-code">{recover_code_label}</label>
    <input id="recovery-code" name="code" type="text" required
           autocomplete="off" inputmode="text"
           pattern="[A-Za-z0-9 \-]+"
           maxlength="13"
           spellcheck="false">
    <button type="submit">{recover_button}</button>
  </form>
</details>"#,
        title              = escape(lookup(MessageKey::TotpVerifyTitle,             locale)),
        intro              = escape(lookup(MessageKey::TotpVerifyIntro,             locale)),
        heading            = escape(lookup(MessageKey::TotpVerifyHeading,           locale)),
        code_label         = escape(lookup(MessageKey::TotpVerifyCodeLabel,         locale)),
        continue_button    = escape(lookup(MessageKey::TotpVerifyContinueButton,    locale)),
        lost_summary       = escape(lookup(MessageKey::TotpVerifyLostSummary,       locale)),
        recover_intro      = escape(lookup(MessageKey::TotpVerifyRecoverIntro,      locale)),
        recover_aria       = escape(lookup(MessageKey::TotpVerifyRecoverAriaLabel,  locale)),
        recover_code_label = escape(lookup(MessageKey::TotpVerifyRecoverCodeLabel,  locale)),
        recover_button     = escape(lookup(MessageKey::TotpVerifyRecoverButton,     locale)),
        error_block        = error_block,
        csrf               = escape(csrf_token),
    );
    frame_for(lookup(MessageKey::TotpVerifyPageTitleHtml, locale), &body, locale)
}

/// TOTP disable confirmation page. Shown by `GET /me/security/totp/disable`
/// when the user requests TOTP removal. The form POSTs to the same
/// path; on success the worker deletes the user's TOTP authenticators
/// + recovery codes and redirects with a success notice.
///
/// Disabling TOTP is destructive in the sense that the user loses
/// MFA on their account, and any unredeemed recovery codes are
/// also wiped. The page emphasizes both consequences and requires
/// an explicit confirm click — no "are you sure" double-prompt
/// (one click is enough; the consequences are clearly stated and
/// re-enrolling takes one minute).
///
/// `csrf_token` matches the `__Host-cesauth-csrf` cookie value
/// for the POST guard. v0.30.0 surface.
pub fn totp_disable_confirm_page(csrf_token: &str) -> String {
    totp_disable_confirm_page_for(csrf_token, cesauth_core::i18n::Locale::default())
}

/// **v0.47.0** — Locale-aware variant of
/// [`totp_disable_confirm_page`]. The cancel link reuses
/// the existing `TotpEnrollCancelLink` MessageKey
/// ("キャンセルして戻る" / "Cancel and go back") rather
/// than introducing a duplicate — the i18n catalog
/// uniqueness invariant (no two MessageKey variants
/// resolve to the same string within a locale) catches
/// duplicates as test failures.
pub fn totp_disable_confirm_page_for(
    csrf_token: &str,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let body = format!(
        r#"<h1>{heading}</h1>
<div class="warning" role="alert" aria-live="polite">
  <strong>{alert_strong}</strong>
  {alert_body}
</div>

<p>{recovery_hint}</p>

<form method="POST" action="/me/security/totp/disable" aria-labelledby="disable-heading">
  <h2 id="disable-heading" class="muted">{confirm_heading}</h2>
  <input type="hidden" name="csrf" value="{csrf}">
  <button type="submit" class="danger">{submit}</button>
</form>

<p class="muted"><a href="/">{cancel}</a></p>"#,
        heading         = escape(lookup(MessageKey::TotpDisableHeading,         locale)),
        alert_strong    = escape(lookup(MessageKey::TotpDisableAlertStrong,    locale)),
        alert_body      = escape(lookup(MessageKey::TotpDisableAlertBody,      locale)),
        recovery_hint   = escape(lookup(MessageKey::TotpDisableRecoveryHint,   locale)),
        confirm_heading = escape(lookup(MessageKey::TotpDisableConfirmHeading, locale)),
        submit          = escape(lookup(MessageKey::TotpDisableSubmit,         locale)),
        cancel          = escape(lookup(MessageKey::TotpEnrollCancelLink,      locale)),
        csrf            = escape(csrf_token),
    );
    frame_for(lookup(MessageKey::TotpDisablePageTitle, locale), &body, locale)
}

// =====================================================================
