[workspace]

[package]
name = "cesauth"
version = "0.1.0"

description = "Authentication and authorization web service aiming robustness, performance and scalability written in rust."
authors = ["nabbisen <nabbisen@scqr.net>"]
edition = "2021"

publish = false
default-run = "cesauth-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
loco-rs = { version = "^0.14" }

[dependencies]
loco-rs = { workspace = true  }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1", default-features = false, features = [
  "rt-multi-thread",
] }
async-trait = { version = "^0.1" }
axum = { version = "^0.8" }
tracing = { version = "^0.1" }
tracing-subscriber = { version = "^0.3", features = ["env-filter", "json"] }
regex = { version = "1" }
migration = { path = "migration" }
sea-orm = { version = "1", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
chrono = { version = "^0.4" }
validator = { version = "^0.19" }
uuid = { version = "1", features = ["v4"] }
include_dir = { version = "^0.7" }
# view engine i18n
fluent-templates = { version = "^0.8", features = ["tera"] }
unic-langid = { version = "^0.9" }
# /view engine

[[bin]]
name = "cesauth-cli"
path = "src/bin/main.rs"
required-features = []

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = { version = "3" }
rstest = { version = "^0.21" }
insta = { version = "1", features = ["redactions", "yaml", "filters"] }
