//! Generated by RFC 098 split.

use crate::{escape, js_string_literal};
use super::chrome::frame_for;

/// Page shown after a Magic Link has been sent. Does not reveal whether
/// the email existed (account enumeration mitigation).
///
/// `handle` is the AuthChallenge handle from the prior `/magic-link/request`
/// step. The verify endpoint needs it to look up the challenge.
/// `csrf_token` is the CSRF token (matching the
/// `__Host-cesauth-csrf` cookie) required by `/magic-link/verify`'s
/// form-encoded path. Both fields land as hidden inputs so the
/// browser carries them on submission.
///
/// Pre-v0.25.0 this template took no arguments and rendered a form
/// missing both fields, which made the form-flow path unusable in
/// browsers (the verify handler returns 400 on empty handle, and
/// the v0.24.0 CSRF gap fill rejects empty csrf). The path was
/// failing closed but invisible-to-users. v0.25.0 fixes the UX and
/// adds an end-to-end form test (see `tests.rs`).
pub fn magic_link_sent_page(handle: &str, csrf_token: &str) -> String {
    magic_link_sent_page_for(handle, csrf_token, None, cesauth_core::i18n::Locale::default())
}

/// **v0.47.0** — Locale-aware variant of
/// [`magic_link_sent_page`]. Pre-v0.47.0 this page was
/// EN-only despite cesauth's "default JA" pattern; the
/// migration to the catalog brings it in line with the
/// rest of the user-facing surfaces. The legacy
/// shorthand calls this with `Locale::default()` (Ja),
/// which is **a behavior change in display** for any
/// caller still on the shorthand — they previously got
/// English, now they get Japanese. The worker
/// handlers were already negotiating locale in v0.39.0
/// and pass through `_for`, so the production path is
/// unaffected.
///
/// **v0.78.5** — added `error: Option<&str>` so the verify handler
/// can re-render the form with an inline error message instead of
/// returning a raw JSON 400 to the browser.
pub fn magic_link_sent_page_for(
    handle: &str,
    csrf_token: &str,
    error: Option<&str>,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let error_html = error
        .map(|msg| format!("<p role=\"alert\" class=\"form-error\">{}</p>\n", escape(msg)))
        .unwrap_or_default();
    let body = format!(
        r#"
<h1>{heading}</h1>
<p>{intro}</p>
{error_html}
<form method="POST" action="{verify_url}" aria-labelledby="otp-heading">
  <h2 id="otp-heading" class="muted">{otp_heading}</h2>
  <input type="hidden" name="handle" value="{handle}">
  <input type="hidden" name="csrf"   value="{csrf}">
  <label for="code">{code_label}</label>
  <input id="code" name="code" type="text" required autocomplete="one-time-code"
         inputmode="text" spellcheck="false" pattern="[A-Za-z0-9]{{6,12}}">
  <button type="submit">{submit}</button>
</form>
"#,
        heading     = escape(lookup(MessageKey::MagicLinkSentHeading,    locale)),
        intro       = escape(lookup(MessageKey::MagicLinkSentIntro,      locale)),
        otp_heading = escape(lookup(MessageKey::MagicLinkSentOtpHeading, locale)),
        code_label  = escape(lookup(MessageKey::MagicLinkSentCodeLabel,  locale)),
        submit      = escape(lookup(MessageKey::TotpVerifyContinueButton, locale)),
        handle      = escape(handle),
        csrf        = escape(csrf_token),
        verify_url  = cesauth_core::routes::auth::MAGIC_LINK_VERIFY_FORM,
        error_html  = error_html,
    );
    frame_for(lookup(MessageKey::MagicLinkSentPageTitle, locale), &body, locale)
}

/// Generic error page. The worker layer maps specific errors to strings
/// (we do not leak internal detail here).
pub fn error_page(title: &str, detail: &str) -> String {
    error_page_for(title, detail, cesauth_core::i18n::Locale::default())
}

/// **v0.47.0** — Locale-aware variant of [`error_page`].
/// `title` and `detail` are caller-supplied (the worker
/// is responsible for localizing them before passing in);
/// only the "back to sign in" link is templated through
/// the catalog.
pub fn error_page_for(
    title: &str,
    detail: &str,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};
    let body = format!(
        r#"<h1>{title}</h1>
<div class="error" role="alert" aria-live="assertive">{detail}</div>
<p><a href="/">{back}</a></p>"#,
        title  = escape(title),
        detail = escape(detail),
        back   = escape(lookup(MessageKey::ErrorPageBackLink, locale)),
    );
    frame_for(title, &body, locale)
}

// =====================================================================
