//! Generated by RFC 098 split.
//!
//! v0.67.0 (RFC 106): TOTP enabled-state badge / disable link / recovery
//! 0-and-1 banners are now sourced from the i18n catalog, closing the
//! JA-hardcode hole deferred from v0.39.0. The N≥2 recovery template
//! still carries `{n}` for substitution; true plural-form handling
//! waits for RFC 107 (ADR-013 §Q4).

use crate::escape;
use super::chrome::frame_with_flash;

// /me/security — Security Center index page (v0.31.0 P0-A)
// =====================================================================

/// Primary authentication method for the current session — used
/// by the Security Center to label "how you sign in". Surfaces
/// only as display copy; no security decision rides on this
/// value. Set by the worker from the session record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PrimaryAuthMethod {
    /// WebAuthn / Passkey. Already MFA-strong (device possession
    /// + on-device user verification), so TOTP is bypassed in
    /// `complete_auth`.
    Passkey,
    /// Magic Link via email. TOTP gate applies on top of this.
    MagicLink,
    /// Anonymous trial principal. Cannot enroll TOTP; the page
    /// renders without TOTP controls.
    Anonymous,
}

impl PrimaryAuthMethod {
    /// **v0.31.0** — JA-default label. Pre-v0.47.0 this
    /// was the only accessor; locale-aware code now uses
    /// [`Self::label_for`]. Retained as the
    /// default-locale shorthand for callers that haven't
    /// been migrated to negotiated locales.
    #[allow(dead_code)]
    fn label(self) -> &'static str {
        self.label_for(cesauth_core::i18n::Locale::default())
    }

    /// **v0.47.0** — i18n-2 continuation. Locale-aware
    /// label dispatch. The Security Center template's
    /// `_for(.., locale)` variants thread their locale
    /// through to this getter.
    pub fn label_for(self, locale: cesauth_core::i18n::Locale) -> &'static str {
        use cesauth_core::i18n::{lookup, MessageKey};
        match self {
            Self::Passkey   => lookup(MessageKey::PrimaryAuthMethodPasskey,   locale),
            Self::MagicLink => lookup(MessageKey::PrimaryAuthMethodMagicLink, locale),
            Self::Anonymous => lookup(MessageKey::PrimaryAuthMethodAnonymous, locale),
        }
    }
}

/// View state for [`security_center_page`]. Built by the worker
/// handler from the session + TOTP repo lookups; the template is
/// a pure projection of this struct.
///
/// `recovery_codes_remaining` is the result of
/// `RecoveryRepo::count_remaining` for the current user. Only
/// meaningful when `totp_enabled` is `true` — the rendering
/// suppresses the recovery section when TOTP is off, since
/// unconfirmed users have no codes.
#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
pub struct SecurityCenterState {
    pub primary_method:           PrimaryAuthMethod,
    pub totp_enabled:             bool,
    pub recovery_codes_remaining: u32,
    /// **RFC 075** — Active session count for the current user.
    /// Populated by the worker handler via the session-index store.
    /// `None` if the count is unavailable (e.g. DO temporarily unreachable).
    pub active_sessions_count:    Option<u32>,
}

/// Same as [`security_center_page`] but allows the caller to
/// splice a flash banner above the page content. The Security
/// TOTP subsection of the Security Center. Branches on
/// `enabled`; when enabled, also renders the recovery-codes
/// status row with the 4-tier threshold treatment from plan
/// §3.1 P0-A.
///
/// **RFC 106 (v0.67.0)** — Every visible string now flows through
/// the i18n catalog, closing the JA-hardcode hole that v0.39.0
/// deferred. The N≥2 recovery template still carries `{n}` for
/// substitution; true plural-form handling is RFC 107's scope.
fn totp_section_html_for(
    enabled: bool,
    recovery_remaining: u32,
    locale: cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    if !enabled {
        return format!(
            r#"<section class="security-row" aria-labelledby="totp-heading">
  <h2 id="totp-heading">{heading}</h2>
  <p>
    <span class="badge badge--info">
      <span aria-hidden="true">ⓘ</span>
      <span>{badge}</span>
    </span>
  </p>
  <p>{intro}</p>
  <p><a href="{enable_url}">{enable_link}</a></p>
</section>"#,
            heading     = escape(lookup(MessageKey::SecurityTotpHeading,         locale)),
            badge       = escape(lookup(MessageKey::SecurityTotpDisabledBadge,   locale)),
            intro       = escape(lookup(MessageKey::SecurityTotpDisabledIntro,   locale)),
            enable_link = escape(lookup(MessageKey::SecurityTotpEnableLink,      locale)),
            enable_url  = cesauth_core::routes::me::TOTP_ENROLL,
        );
    }

    let recovery_row = recovery_status_html_for(recovery_remaining, locale);

    // Enabled path — all visible strings via the catalog (RFC 106).
    format!(
        r#"<section class="security-row" aria-labelledby="totp-heading">
  <h2 id="totp-heading">{heading}</h2>
  <p>
    <span class="badge badge--success">
      <span aria-hidden="true">✓</span>
      <span>{enabled_badge}</span>
    </span>
  </p>
  {recovery_row}
  <p><a href="{disable_url}">{disable_link}</a></p>
</section>"#,
        heading       = escape(cesauth_core::i18n::lookup(
            cesauth_core::i18n::MessageKey::SecurityTotpHeading,       locale)),
        enabled_badge = escape(cesauth_core::i18n::lookup(
            cesauth_core::i18n::MessageKey::SecurityTotpEnabledBadge,  locale)),
        disable_link  = escape(cesauth_core::i18n::lookup(
            cesauth_core::i18n::MessageKey::SecurityTotpDisableLink,   locale)),
        disable_url   = cesauth_core::routes::me::TOTP_DISABLE,
        recovery_row  = recovery_row,
    )
}

/// Recovery-codes status block. Four-tier rendering per plan
/// §3.1 P0-A:
///
/// - N=10 → info badge, no supporting text (initial state).
/// - N=2–9 → info badge with the count, no supporting text.
/// - N=1 → warning badge + supporting text encouraging
///   re-enrollment. This is the first tier where the action
///   ("re-enroll") is truly justified.
/// - N=0 → danger badge + clear "operator contact required"
///   message.
///
/// All visible strings come from the i18n catalog (RFC 106 closure of
/// the v0.39.0 deferral). The N=1 / N=0 banners use a paired strong-title
/// + detail pattern (`SecurityRecoveryZeroTitle` + `SecurityRecoveryZeroDetail`,
/// and similarly for N=1) so translators can adjust emphasis independently.
/// The N≥2 path uses `lookup_plural` (RFC 107) — EN renders
/// `2 valid recovery codes` (plural agreement with the count), JA renders
/// the plural-invariant `リカバリーコード: {n} 個有効`.
fn recovery_status_html_for(n: u32, locale: cesauth_core::i18n::Locale) -> String {
    use cesauth_core::i18n::{lookup, lookup_plural, MessageKey};
    match n {
        0 => format!(
            r#"<div class="flash flash--danger" role="alert" aria-live="assertive">
    <span class="flash__icon" aria-hidden="true">⛔</span>
    <span class="flash__text">
      <strong>{title}</strong>
      {detail}
    </span>
  </div>"#,
            title  = escape(lookup(MessageKey::SecurityRecoveryZeroTitle,  locale)),
            detail = escape(lookup(MessageKey::SecurityRecoveryZeroDetail, locale)),
        ),

        1 => format!(
            r#"<div class="flash flash--warning" role="alert" aria-live="assertive">
    <span class="flash__icon" aria-hidden="true">⚠</span>
    <span class="flash__text">
      <strong>{title}</strong>
      {detail}
    </span>
  </div>"#,
            title  = escape(lookup(MessageKey::SecurityRecoveryOneTitle,  locale)),
            detail = escape(lookup(MessageKey::SecurityRecoveryOneDetail, locale)),
        ),

        n => {
            // RFC 107 (ADR-013 §Q4 plural closure): pick the catalog
            // entry matching this `(locale, n)` pair — EN gets the
            // plural agreement, JA stays plural-invariant.
            let template = lookup_plural(MessageKey::SecurityRecoveryRemaining, locale, n as u64);
            let label = template.replace("{n}", &n.to_string());
            format!(
                r#"<p>
    <span class="badge badge--info">
      <span aria-hidden="true">ⓘ</span>
      <span>{label}</span>
    </span>
  </p>"#,
                label = escape(&label),
            )
        }
    }
}


// =====================================================================
// v0.35.0 — /me/security/sessions page
// =====================================================================

/// One row in the active-sessions list. The handler builds these
/// from `SessionState` rows returned by
/// `ActiveSessionStore::list_for_user`. Kept here (vs. importing
/// `SessionState` directly) so the template's contract is
/// surface-stable: future changes to `SessionState` shape won't
/// silently change what the user sees.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SessionListItem {
    pub session_id:    String,
    pub auth_method:   String,   // "passkey" | "magic_link" | "admin"
    pub client_id:     String,   // displayed; empty string is fine
    pub created_at:    i64,      // Unix seconds
    pub last_seen_at:  i64,      // Unix seconds; matches created_at on D1-projected rows
    /// `true` if this row is the session that's currently
    /// rendering the page. Surfaced as a "this device" badge
    /// and disables the row's revoke button (revoking your
    /// current session would just log you out — handle that
    /// via the regular logout flow).
    pub is_current:    bool,
}

#[allow(dead_code)]
fn render_session_row(s: &SessionListItem, csrf_token: &str) -> String {
    render_session_row_for(s, csrf_token, cesauth_core::i18n::Locale::default())
}

fn render_session_row_for(
    s:          &SessionListItem,
    csrf_token: &str,
    locale:     cesauth_core::i18n::Locale,
) -> String {
    use cesauth_core::i18n::{lookup, MessageKey};

    let method_label = match s.auth_method.as_str() {
        "passkey"    => lookup(MessageKey::SessionsAuthMethodPasskey,   locale),
        "magic_link" => lookup(MessageKey::SessionsAuthMethodMagicLink, locale),
        "admin"      => lookup(MessageKey::SessionsAuthMethodAdmin,     locale),
        _            => lookup(MessageKey::SessionsAuthMethodUnknown,   locale),
    };
    // RFC 111 (ADR-013 §Q4 date-side closure): every visible timestamp
    // goes through the canonical UTC ISO-8601 formatter. Per-user
    // timezone is future work; the policy is documented in
    // docs/src/expert/i18n.md §"Date / time rendering".
    let created = cesauth_core::util::format_unix_as_iso8601(s.created_at);
    let last    = cesauth_core::util::format_unix_as_iso8601(s.last_seen_at);

    let badge = if s.is_current {
        format!(
            r##"<span class="badge badge--current" aria-label="{badge_text}">{badge_text}</span>"##,
            badge_text = escape(lookup(MessageKey::SessionsCurrentBadge, locale)),
        )
    } else {
        String::new()
    };

    // Current session's revoke button is disabled — the user
    // should log out via the normal flow instead. If we let
    // them revoke their own session, the next request would
    // redirect to /login and the action would feel
    // self-defeating; logout-via-known-button is better UX.
    let action = if s.is_current {
        format!(
            r##"<button type="button" class="muted" disabled aria-disabled="true" title="{title}">{label}</button>"##,
            title = escape(lookup(MessageKey::SessionsCurrentDisabledTitle, locale)),
            label = escape(lookup(MessageKey::SessionsCurrentDisabled,      locale)),
        )
    } else {
        format!(
            r##"<form method="post" action="{revoke_url}" class="inline-form">
  <input type="hidden" name="csrf" value="{csrf}">
  <button type="submit" class="warning">{revoke}</button>
</form>"##,
            // The catalog builder returns a URL with the session_id
            // interpolated verbatim; HTML-escape at the boundary so a
            // pathological session_id can't break out of the attribute.
            revoke_url = escape(&cesauth_core::routes::me::session_revoke(&s.session_id)),
            csrf   = escape(csrf_token),
            revoke = escape(lookup(MessageKey::SessionsRevokeButton, locale)),
        )
    };

    format!(
        r##"<article class="session-card" aria-label="セッション {sid}">
  <header>
    <strong>{method}</strong> {badge}
  </header>
  <dl class="session-meta">
    <dt>{l_signin}</dt><dd>{created}</dd>
    <dt>{l_last}</dt><dd>{last}</dd>
    <dt>{l_client}</dt><dd><code>{client}</code></dd>
    <dt>{l_sid}</dt><dd><code>{sid_short}</code></dd>
  </dl>
  <footer>{action}</footer>
</article>"##,
        sid       = escape(&s.session_id),
        sid_short = escape(&shorten_id(&s.session_id)),
        method    = escape(method_label),
        badge     = badge,
        created   = escape(&created),
        last      = escape(&last),
        client    = escape(&s.client_id),
        action    = action,
        l_signin  = escape(lookup(MessageKey::SessionsLabelSignIn,     locale)),
        l_last    = escape(lookup(MessageKey::SessionsLabelLastSeen,   locale)),
        l_client  = escape(lookup(MessageKey::SessionsLabelClient,     locale)),
        l_sid     = escape(lookup(MessageKey::SessionsLabelSessionId,  locale)),
    )
}

/// Truncate a UUID-shaped session_id to the first 8 chars for
/// display. The full id is in the form action's URL; the
/// shortened version is just visual chrome.
fn shorten_id(id: &str) -> String {
    let mut out: String = id.chars().take(8).collect();
    if id.chars().count() > 8 { out.push('…'); }
    out
}


